### ISSUE TITLE
How to convert actual coordinates to map coordinates?

### ISSUE THREAD

**Issue by FrankyLee-dev** [ninepatch/IndoorMapView#4]
I loaded an image, but I don't know how to convert the Marker's coordinates to the map.

**Comment by RurioLuca** [comment]
you should give your coordinates from the center of your image.
Since it is not a geographic map it remains very difficult to load pre-established markers, as the coordinates vary depending on the image loaded.
You should extrapolate the coordinates to the click on the map where you want to place the markers, to perform a preloading of the markers.

I think it's a problem related to all these types of maps, if you have any advice I'll be happy to add them to the library

**Comment by FrankyLee-dev** [comment]
thanks for your suggestions.
 If I have a real terrain 50 m * 20 m, the picture is a 1800 px * 700 px, then set the picture center coordinates is 900,350?
```indoorMapsView.setCenter(900, 350);```

**Comment by RurioLuca** [comment]
if the image is a square and has adapted well to the container the center is lat: 0, lng: 0

**Comment by FrankyLee-dev** [comment]
Ok! I see, thanks!
